random_topology: True 
random_mode: "random.log_degree" 
num_routers: 20 
random_weight_mode: "random"
random_gen_method: 1 
php: True 
ldp: False 
rsvp: True 
rsvp_num_lsps: 25 
rsvp_tunnels_per_pair: 3 
vpn: True 
vpn_num_services: 7 
vpn_pes_per_services: 4 
vpn_ces_per_pe: 3 
random_seed_gen: 321354
